"""fix computer_specs delete cascade

Revision ID: 6acf65e34dc1
Revises: 1516bde17c4d
Create Date: 2024-10-07 20:44:53.218791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acf65e34dc1'
down_revision: Union[str, None] = '1516bde17c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_id', table_name='employee')
    op.drop_table('employee')
    op.drop_index('ix_computer_specs_id', table_name='computer_specs')
    op.drop_table('computer_specs')
    op.drop_index('ix_department_id', table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('department_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='department_pkey'),
    sa.UniqueConstraint('name', name='department_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_department_id', 'department', ['id'], unique=False)
    op.create_table('computer_specs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('computer_specs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cpu', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ram', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('ram > 0', name='check_ram_positive'),
    sa.CheckConstraint('storage > 0', name='check_storage_positive'),
    sa.PrimaryKeyConstraint('id', name='computer_specs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_computer_specs_id', 'computer_specs', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('computer_specs_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['computer_specs_id'], ['computer_specs.id'], name='employee_computer_specs_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='employee_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_pkey'),
    sa.UniqueConstraint('email', name='employee_email_key')
    )
    op.create_index('ix_employee_id', 'employee', ['id'], unique=False)
    # ### end Alembic commands ###
